### ISSUE TITLE
Tests won't run, Error: cannot find module 'livedb'

### ISSUE THREAD

**Issue by mrluc** [codeparty/racer-access#1]
If you do a clean install,

``` sh
$ git clone git@github.com:codeparty/racer-access
$ cd racer-access
$ npm install
```

and try to run tests ... you are boned.

``` sh
$ make
./node_modules/.bin/mocha \
        --reporter spec \
        --grep "" \
        --compilers .coffee:coffee-script \
        ./test/*.coffee | tee

module.js:340
    throw err;
          ^
Error: Cannot find module 'livedb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mrluc/scratch/racer-access/node_modules/racer/node_modules/share/lib/server/index.js:3:14)
    at Module._compile (module.js:456:26) 
    ...
```

Maybe related to https://github.com/share/livedb/issues/4

**Comment by mrluc** [comment]
So - changing package.json to livedb version 0.1.5 fixed this. Apparently something broke in livedb 0.1.6?

Toodle-pip.

**Comment by josephg** [comment]
Yeah, the package.json was / is pulling from git, which means the coffeescript in livedb doesn't get compiled. Livedb will be ported to native javascript soon, and as the API changes calm down between the various projects the versions of everything in npm will make more sense.
